import { ArrowRight, Armchair, Building2, Check, ChevronDown, Layers3, MapPin, MessageCircle, ShieldCheck } from 'lucide-react';
import { Link } from 'react-router-dom';
import { SEOMeta } from '@/components/SEOMeta';
import { ServicePageSchema } from '@/components/ServicePageSchema';
import { businessConfig, whatsappUrl } from '@/config/business';
import { businessCarpetCleaningFaqs } from '@/content/servicePages';
import { businessCarpetCleaningSEO } from '@/config/seo';

const budgetUrl = whatsappUrl('Hola, quiero solicitar un presupuesto de limpieza de moquetas para una empresa.');
const spaces = ['Oficinas', 'Despachos', 'Salas de reuniones', 'Clínicas', 'Comercios', 'Recepciones', 'Centros de trabajo'];
const benefits = [
  ['Mejor aspecto', 'Ayuda a recuperar una presencia más cuidada en zonas de trabajo y atención.'],
  ['Higiene del espacio', 'Retira suciedad acumulada mediante un tratamiento adaptado al tejido.'],
  ['Cuidado de las fibras', 'El método se valora según el material y el estado de la moqueta.'],
  ['Zonas de tránsito', 'Permite prestar atención a pasillos, accesos y áreas de uso frecuente.'],
];

export function BusinessCarpetCleaningPage() {
  return <>
    <SEOMeta config={businessCarpetCleaningSEO} />
    <ServicePageSchema name="Limpieza profesional de moquetas para empresas" serviceType="Limpieza de moquetas, alfombras y tapicerías de oficina" path="/limpieza-de-moquetas-empresas/" breadcrumbName="Limpieza de moquetas para empresas" faqs={businessCarpetCleaningFaqs} />

    <section className="relative isolate overflow-hidden bg-brand-950 px-4 pb-24 pt-36 text-white sm:px-6 lg:px-8"><div className="absolute inset-0 -z-10 bg-[radial-gradient(circle_at_78%_25%,rgba(16,185,129,0.27),transparent_35%)]" /><div className="mx-auto max-w-7xl"><nav aria-label="Migas de pan" className="mb-10 flex items-center gap-2 text-sm text-slate-400"><Link to="/" className="transition hover:text-brand-400">Inicio</Link><span aria-hidden="true">/</span><span className="text-slate-200">Limpieza de moquetas para empresas</span></nav><div className="grid items-center gap-12 lg:grid-cols-[1.15fr_.85fr]"><div><p className="inline-flex items-center gap-2 rounded-full border border-brand-400/30 bg-brand-400/10 px-4 py-2 text-sm font-semibold text-brand-400"><Layers3 className="h-4 w-4" aria-hidden="true" /> Especialistas en limpieza textil</p><h1 className="mt-6 max-w-4xl text-4xl font-black leading-[1.08] tracking-tight sm:text-5xl lg:text-6xl">Limpieza profesional de moquetas para empresas</h1><p className="mt-6 max-w-2xl text-lg leading-8 text-slate-300">La experiencia textil de Superclim aplicada a moquetas, sillas y tapicerías de oficinas y espacios profesionales en Sabadell, Barcelona y Vallès.</p><div className="mt-9 flex flex-col gap-3 sm:flex-row"><a href={budgetUrl} target="_blank" rel="noreferrer" className="inline-flex min-h-12 items-center justify-center gap-2 rounded-full bg-gradient-to-r from-brand-600 to-teal-500 px-6 py-3.5 font-bold shadow-soft transition hover:brightness-110">Solicitar presupuesto <ArrowRight className="h-5 w-5" /></a><a href={budgetUrl} target="_blank" rel="noreferrer" className="inline-flex min-h-12 items-center justify-center gap-2 rounded-full border border-white/20 bg-white/5 px-6 py-3.5 font-bold transition hover:bg-white/10"><MessageCircle className="h-5 w-5 text-brand-400" /> WhatsApp</a></div></div><div className="rounded-3xl border border-white/10 bg-white/[0.07] p-7 backdrop-blur sm:p-9"><Armchair className="h-10 w-10 text-brand-400" /><p className="mt-6 text-sm font-bold uppercase tracking-[0.18em] text-brand-400">Textiles profesionales</p><ul className="mt-6 space-y-4 text-slate-200">{['Moquetas corporativas', 'Alfombras en zonas comunes', 'Sillas y sillones de oficina', 'Tapicerías y textiles de recepción'].map((item) => <li key={item} className="flex gap-3"><Check className="mt-0.5 h-5 w-5 shrink-0 text-brand-400" />{item}</li>)}</ul></div></div></div></section>

    <nav aria-label="Contenido de la página" className="border-b border-slate-200 bg-white px-4 sm:px-6 lg:px-8"><div className="mx-auto flex max-w-7xl gap-2 overflow-x-auto py-4"><a href="#aplicaciones" className="shrink-0 rounded-full bg-brand-50 px-4 py-2 text-sm font-bold text-brand-700">Aplicaciones</a><a href="#metodo" className="shrink-0 rounded-full bg-brand-50 px-4 py-2 text-sm font-bold text-brand-700">Método</a><Link to={businessConfig.urls.businessServices.offices} className="shrink-0 rounded-full bg-slate-100 px-4 py-2 text-sm font-bold text-slate-700">Oficinas</Link></div></nav>

    <section id="aplicaciones" className="scroll-mt-24 px-4 py-24 sm:px-6 lg:px-8"><div className="mx-auto max-w-7xl"><div className="max-w-3xl"><p className="text-sm font-extrabold uppercase tracking-[0.2em] text-brand-600">Dónde se aplica</p><h2 className="mt-3 text-3xl font-black tracking-tight sm:text-4xl">Moquetas en espacios de uso profesional</h2><p className="mt-5 text-lg leading-8 text-slate-600">El servicio se adapta a espacios con diferentes niveles de tránsito, distribución y mobiliario, después de valorar el tejido y las condiciones de trabajo.</p></div><div className="mt-10 grid gap-4 sm:grid-cols-2 lg:grid-cols-3">{spaces.map((item) => <div key={item} className="flex min-h-20 items-center gap-4 rounded-2xl border border-slate-200 p-5 font-bold shadow-sm"><Building2 className="h-5 w-5 shrink-0 text-brand-600" />{item}</div>)}</div></div></section>

    <section className="bg-slate-50 px-4 py-24 sm:px-6 lg:px-8"><div className="mx-auto max-w-7xl"><div className="mx-auto max-w-3xl text-center"><p className="text-sm font-extrabold uppercase tracking-[0.2em] text-brand-600">Beneficios</p><h2 className="mt-3 text-3xl font-black tracking-tight sm:text-4xl">Cuidar la moqueta mejora el conjunto del espacio</h2><p className="mt-5 text-lg leading-8 text-slate-600">Una limpieza profesional ayuda a tratar la suciedad derivada del uso y a conservar mejor la imagen de las zonas textiles, sin prometer resultados idénticos en todos los materiales.</p></div><div className="mt-12 grid gap-5 sm:grid-cols-2 lg:grid-cols-4">{benefits.map(([title, text]) => <article key={title} className="rounded-2xl bg-white p-7 shadow-sm"><ShieldCheck className="h-7 w-7 text-brand-600" /><h3 className="mt-5 font-bold">{title}</h3><p className="mt-3 text-sm leading-6 text-slate-600">{text}</p></article>)}</div></div></section>

    <section id="metodo" className="scroll-mt-24 px-4 py-24 sm:px-6 lg:px-8"><div className="mx-auto grid max-w-7xl items-center gap-14 lg:grid-cols-2"><div><p className="text-sm font-extrabold uppercase tracking-[0.2em] text-brand-600">Método de trabajo</p><h2 className="mt-3 text-3xl font-black tracking-tight sm:text-4xl">Un tratamiento definido según el textil</h2><p className="mt-5 text-lg leading-8 text-slate-600">Antes de intervenir se valora el tipo de fibra, la instalación, el estado y las zonas de tránsito. Según el caso, el proceso puede incorporar aspirado profundo y limpieza por inyección-extracción, técnicas que Superclim ya aplica en sus servicios textiles.</p><p className="mt-4 leading-7 text-slate-600">La planificación también tiene en cuenta la ventilación y el tiempo de secado estimado para coordinar el servicio con la actividad de la empresa.</p></div><div className="rounded-3xl bg-brand-950 p-8 text-white"><p className="text-sm font-bold uppercase tracking-[0.18em] text-brand-400">Valoración previa</p><ul className="mt-6 space-y-4 text-slate-200">{['Material y tipo de instalación', 'Estado general y suciedad acumulada', 'Zonas de tránsito y mobiliario', 'Ventilación y uso posterior del espacio'].map((item) => <li key={item} className="flex gap-3"><Check className="h-5 w-5 shrink-0 text-brand-400" />{item}</li>)}</ul></div></div></section>

    <section className="bg-brand-950 px-4 py-24 text-white sm:px-6 lg:px-8"><div className="mx-auto grid max-w-7xl items-center gap-12 lg:grid-cols-[.85fr_1.15fr]"><div className="rounded-3xl border border-white/10 bg-white/[0.06] p-8"><Armchair className="h-12 w-12 text-brand-400" /><div className="mt-8 grid grid-cols-2 gap-3">{['Sillas', 'Sillones', 'Bancos', 'Tapizados'].map((item) => <div key={item} className="rounded-xl bg-white/[0.07] p-4 text-sm font-bold">{item}</div>)}</div></div><div><p className="text-sm font-extrabold uppercase tracking-[0.2em] text-brand-400">Sillas y tapicerías</p><h2 className="mt-3 text-3xl font-black tracking-tight sm:text-4xl">El cuidado textil no termina en el suelo</h2><p className="mt-5 text-lg leading-8 text-slate-300">También podemos valorar sillas, sillones, bancos y tapizados corporativos para coordinar la atención a diferentes textiles dentro del mismo espacio profesional.</p></div></div></section>

    <section className="px-4 py-24 sm:px-6 lg:px-8"><div className="mx-auto grid max-w-7xl gap-12 lg:grid-cols-2"><div><p className="text-sm font-extrabold uppercase tracking-[0.2em] text-brand-600">Experiencia Superclim</p><h2 className="mt-3 text-3xl font-black tracking-tight sm:text-4xl">Especialización textil aplicada a empresas</h2><p className="mt-5 text-lg leading-8 text-slate-600">La experiencia de Superclim en el cuidado de tejidos se traslada al ámbito profesional. La misma marca también presta servicios de <a href={businessConfig.urls.privateServices.sofas} className="font-semibold text-brand-700 underline decoration-brand-300 underline-offset-4">limpieza de sofás</a> y <a href={businessConfig.urls.privateServices.carpets} className="font-semibold text-brand-700 underline decoration-brand-300 underline-offset-4">limpieza de alfombras para particulares</a>.</p></div><div className="grid gap-4"><Link to={businessConfig.urls.businessServices.offices} className="group flex items-center justify-between rounded-2xl border border-slate-200 p-6 font-bold transition hover:border-brand-400">Limpieza profesional de oficinas <ArrowRight className="h-5 w-5 text-brand-600 transition group-hover:translate-x-1" /></Link><Link to={businessConfig.urls.businessServices.industrial} className="group flex items-center justify-between rounded-2xl border border-slate-200 p-6 font-bold transition hover:border-brand-400">Limpieza de naves y áreas administrativas <ArrowRight className="h-5 w-5 text-brand-600 transition group-hover:translate-x-1" /></Link></div></div></section>

    <section className="bg-slate-50 px-4 py-24 text-center sm:px-6 lg:px-8"><MapPin className="mx-auto h-9 w-9 text-brand-600" /><h2 className="mt-5 text-3xl font-black tracking-tight sm:text-4xl">Servicio en Barcelona, Sabadell y Vallès</h2><p className="mx-auto mt-5 max-w-3xl text-lg leading-8 text-slate-600">Atendemos empresas en Sabadell, Terrassa, Sant Cugat, Rubí, Cerdanyola, Barberà, Barcelona y otras zonas del Vallès Occidental.</p></section>

    <section className="px-4 py-24 sm:px-6 lg:px-8"><div className="mx-auto max-w-4xl"><div className="text-center"><p className="text-sm font-extrabold uppercase tracking-[0.2em] text-brand-600">Preguntas frecuentes</p><h2 className="mt-3 text-3xl font-black tracking-tight sm:text-4xl">Sobre la limpieza de moquetas</h2></div><div className="mt-12 space-y-3">{businessCarpetCleaningFaqs.map((faq) => <details key={faq.question} className="group rounded-2xl border border-slate-200 bg-white p-5 open:border-brand-300"><summary className="flex cursor-pointer list-none items-center justify-between gap-4 font-bold focus-visible:outline-none">{faq.question}<ChevronDown className="h-5 w-5 shrink-0 text-brand-600 transition group-open:rotate-180" /></summary><p className="mt-4 pr-8 leading-7 text-slate-600">{faq.answer}</p></details>)}</div></div></section>

    <section className="px-4 pb-24 sm:px-6 lg:px-8"><div className="mx-auto max-w-5xl rounded-3xl bg-gradient-to-br from-brand-700 to-teal-600 px-7 py-14 text-center text-white shadow-soft sm:px-12"><p className="text-sm font-extrabold uppercase tracking-[0.2em] text-emerald-100">Presupuesto personalizado</p><h2 className="mt-3 text-3xl font-black tracking-tight sm:text-4xl">Cuéntanos qué textiles necesita cuidar tu empresa</h2><p className="mx-auto mt-4 max-w-2xl text-lg leading-8 text-emerald-50">Valoraremos material, superficie, mobiliario y uso para preparar una propuesta adaptada.</p><a href={budgetUrl} target="_blank" rel="noreferrer" className="mt-8 inline-flex min-h-12 items-center gap-2 rounded-full bg-white px-7 py-3.5 font-bold text-brand-700">Solicitar presupuesto <ArrowRight className="h-5 w-5" /></a></div></section>
  </>;
}
