import { ArrowRight, Building2, CalendarCheck, Check, ChevronDown, Clock3, Factory, MapPin, MessageCircle, Repeat2, ShoppingBag, Sparkles } from 'lucide-react';
import { Link } from 'react-router-dom';
import { SEOMeta } from '@/components/SEOMeta';
import { ServicePageSchema } from '@/components/ServicePageSchema';
import { businessConfig, whatsappUrl } from '@/config/business';
import { cleaningMaintenanceFaqs } from '@/content/servicePages';
import { cleaningMaintenanceSEO } from '@/config/seo';

const budgetUrl = whatsappUrl('Hola, quiero solicitar un presupuesto de mantenimiento de limpieza para mi empresa.');
const frequencies = [
  ['Puntual', 'Para una necesidad concreta o una puesta a punto planificada.'],
  ['Semanal', 'Para espacios que requieren una atención recurrente a lo largo del mes.'],
  ['Diaria cuando proceda', 'En centros cuyo uso y actividad justifican una frecuencia mayor.'],
  ['Personalizada', 'Una planificación ajustada a zonas, tránsito y prioridades reales.'],
];
const areas = ['Zonas de trabajo', 'Áreas de atención', 'Aseos', 'Zonas comunes', 'Recepciones', 'Áreas administrativas'];

export function CleaningMaintenancePage() {
  return <>
    <SEOMeta config={cleaningMaintenanceSEO} />
    <ServicePageSchema name="Mantenimiento de limpieza para empresas" serviceType="Servicio periódico de limpieza para empresas" path="/mantenimiento-de-limpieza/" breadcrumbName="Mantenimiento de limpieza" faqs={cleaningMaintenanceFaqs} />

    <section className="relative isolate overflow-hidden bg-brand-950 px-4 pb-24 pt-36 text-white sm:px-6 lg:px-8"><div className="absolute inset-0 -z-10 bg-[radial-gradient(circle_at_78%_25%,rgba(16,185,129,0.27),transparent_35%)]" /><div className="mx-auto max-w-7xl"><nav aria-label="Migas de pan" className="mb-10 flex items-center gap-2 text-sm text-slate-400"><Link to="/" className="hover:text-brand-400">Inicio</Link><span aria-hidden="true">/</span><span className="text-slate-200">Mantenimiento de limpieza</span></nav><div className="grid items-center gap-12 lg:grid-cols-[1.15fr_.85fr]"><div><p className="inline-flex items-center gap-2 rounded-full border border-brand-400/30 bg-brand-400/10 px-4 py-2 text-sm font-semibold text-brand-400"><Repeat2 className="h-4 w-4" /> Servicio periódico para empresas</p><h1 className="mt-6 max-w-4xl text-4xl font-black leading-[1.08] tracking-tight sm:text-5xl lg:text-6xl">Mantenimiento de limpieza para empresas</h1><p className="mt-6 max-w-2xl text-lg leading-8 text-slate-300">Un servicio recurrente y flexible para conservar oficinas, naves, locales y zonas comunes, con frecuencias y horarios acordados según la actividad.</p><div className="mt-9 flex flex-col gap-3 sm:flex-row"><a href={budgetUrl} target="_blank" rel="noreferrer" className="inline-flex min-h-12 items-center justify-center gap-2 rounded-full bg-gradient-to-r from-brand-600 to-teal-500 px-6 py-3.5 font-bold shadow-soft hover:brightness-110">Solicitar presupuesto <ArrowRight className="h-5 w-5" /></a><a href={budgetUrl} target="_blank" rel="noreferrer" className="inline-flex min-h-12 items-center justify-center gap-2 rounded-full border border-white/20 bg-white/5 px-6 py-3.5 font-bold hover:bg-white/10"><MessageCircle className="h-5 w-5 text-brand-400" /> WhatsApp</a></div></div><div className="rounded-3xl border border-white/10 bg-white/[0.07] p-7 sm:p-9"><CalendarCheck className="h-10 w-10 text-brand-400" /><p className="mt-6 text-sm font-bold uppercase tracking-[0.18em] text-brand-400">Planificación adaptada</p><ul className="mt-6 space-y-4 text-slate-200">{['Servicio puntual o periódico', 'Frecuencia según uso', 'Horarios acordados', 'Alcance personalizado'].map((item) => <li key={item} className="flex gap-3"><Check className="h-5 w-5 shrink-0 text-brand-400" />{item}</li>)}</ul></div></div></div></section>

    <nav aria-label="Contenido de la página" className="border-b border-slate-200 px-4 sm:px-6 lg:px-8"><div className="mx-auto flex max-w-7xl gap-2 overflow-x-auto py-4"><a href="#frecuencias" className="shrink-0 rounded-full bg-brand-50 px-4 py-2 text-sm font-bold text-brand-700">Frecuencias</a><a href="#adaptacion" className="shrink-0 rounded-full bg-brand-50 px-4 py-2 text-sm font-bold text-brand-700">Cómo se adapta</a><Link to={businessConfig.urls.businessServices.offices} className="shrink-0 rounded-full bg-slate-100 px-4 py-2 text-sm font-bold">Oficinas</Link></div></nav>

    <section className="px-4 py-24 sm:px-6 lg:px-8"><div className="mx-auto grid max-w-7xl gap-14 lg:grid-cols-2"><div><p className="text-sm font-extrabold uppercase tracking-[0.2em] text-brand-600">Qué es</p><h2 className="mt-3 text-3xl font-black tracking-tight sm:text-4xl">Continuidad sin planes cerrados</h2><p className="mt-5 text-lg leading-8 text-slate-600">Un mantenimiento de limpieza organiza tareas recurrentes para cuidar las zonas acordadas. La frecuencia no se impone: se define según el tamaño, el uso, el tránsito y las prioridades de la empresa.</p><p className="mt-4 leading-7 text-slate-600">También puede combinarse con servicios puntuales cuando el espacio necesita una atención concreta.</p></div><div className="grid grid-cols-1 gap-3 min-[390px]:grid-cols-2">{areas.map((area) => <div key={area} className="flex min-h-20 items-center gap-3 rounded-2xl border border-slate-200 p-4 font-bold shadow-sm"><Check className="h-5 w-5 shrink-0 text-brand-600" />{area}</div>)}</div></div></section>

    <section id="frecuencias" className="scroll-mt-24 bg-slate-50 px-4 py-24 sm:px-6 lg:px-8"><div className="mx-auto max-w-7xl"><div className="mx-auto max-w-3xl text-center"><p className="text-sm font-extrabold uppercase tracking-[0.2em] text-brand-600">Frecuencias adaptadas</p><h2 className="mt-3 text-3xl font-black tracking-tight sm:text-4xl">La periodicidad que requiere cada centro</h2></div><div className="mt-12 grid gap-5 sm:grid-cols-2 lg:grid-cols-4">{frequencies.map(([title, text]) => <article key={title} className="rounded-2xl bg-white p-7 shadow-sm"><Repeat2 className="h-7 w-7 text-brand-600" /><h3 className="mt-5 font-bold">{title}</h3><p className="mt-3 text-sm leading-6 text-slate-600">{text}</p></article>)}</div></div></section>

    <section className="px-4 py-24 sm:px-6 lg:px-8"><div className="mx-auto max-w-7xl"><div className="max-w-3xl"><p className="text-sm font-extrabold uppercase tracking-[0.2em] text-brand-600">Según el espacio</p><h2 className="mt-3 text-3xl font-black tracking-tight sm:text-4xl">Un mantenimiento distinto para cada actividad</h2></div><div className="mt-12 grid gap-5 md:grid-cols-3"><Link to={businessConfig.urls.businessServices.offices} className="group rounded-2xl border border-slate-200 p-7 transition hover:border-brand-400"><Building2 className="h-8 w-8 text-brand-600" /><h3 className="mt-5 text-xl font-bold">Oficinas</h3><p className="mt-3 leading-7 text-slate-600">Zonas de trabajo, recepción, aseos y espacios comunes según el uso diario.</p><span className="mt-5 inline-flex items-center gap-2 text-sm font-bold text-brand-700">Limpieza profesional de oficinas <ArrowRight className="h-4 w-4 group-hover:translate-x-1" /></span></Link><Link to={businessConfig.urls.businessServices.industrial} className="group rounded-2xl border border-slate-200 p-7 transition hover:border-brand-400"><Factory className="h-8 w-8 text-brand-600" /><h3 className="mt-5 text-xl font-bold">Naves y almacenes</h3><p className="mt-3 leading-7 text-slate-600">Zonas de paso, áreas comunes y espacios administrativos acordados.</p><span className="mt-5 inline-flex items-center gap-2 text-sm font-bold text-brand-700">Limpieza de naves industriales <ArrowRight className="h-4 w-4 group-hover:translate-x-1" /></span></Link><Link to={businessConfig.urls.businessServices.retail} className="group rounded-2xl border border-slate-200 p-7 transition hover:border-brand-400"><ShoppingBag className="h-8 w-8 text-brand-600" /><h3 className="mt-5 text-xl font-bold">Locales comerciales</h3><p className="mt-3 leading-7 text-slate-600">Áreas de atención, superficies y zonas internas de cada negocio.</p><span className="mt-5 inline-flex items-center gap-2 text-sm font-bold text-brand-700">Limpieza de locales comerciales <ArrowRight className="h-4 w-4 group-hover:translate-x-1" /></span></Link></div></div></section>

    <section id="adaptacion" className="scroll-mt-24 bg-brand-950 px-4 py-24 text-white sm:px-6 lg:px-8"><div className="mx-auto grid max-w-7xl items-center gap-12 lg:grid-cols-2"><div><Clock3 className="h-10 w-10 text-brand-400" /><p className="mt-7 text-sm font-extrabold uppercase tracking-[0.2em] text-brand-400">Cómo se adapta</p><h2 className="mt-3 text-3xl font-black tracking-tight sm:text-4xl">Alcance, frecuencia y horarios acordados</h2><p className="mt-5 text-lg leading-8 text-slate-300">Antes de empezar se concretan las zonas, las prioridades y el momento más adecuado. El servicio puede estudiarse antes de la apertura, después de la actividad o en franjas combinadas.</p></div><div className="rounded-3xl border border-white/10 bg-white/[0.06] p-8"><ul className="space-y-4 text-slate-200">{['Valoración de las zonas', 'Definición de tareas', 'Frecuencia proporcionada', 'Revisión del alcance cuando cambian las necesidades'].map((item) => <li key={item} className="flex gap-3"><Check className="h-5 w-5 shrink-0 text-brand-400" />{item}</li>)}</ul></div></div></section>

    <section className="px-4 py-24 sm:px-6 lg:px-8"><div className="mx-auto max-w-7xl"><div className="mx-auto max-w-3xl text-center"><p className="text-sm font-extrabold uppercase tracking-[0.2em] text-brand-600">Por qué Superclim</p><h2 className="mt-3 text-3xl font-black tracking-tight sm:text-4xl">Experiencia y atención personalizada</h2></div><div className="mt-12 grid gap-5 sm:grid-cols-2 lg:grid-cols-4">{[['Más de 16 años', 'Trayectoria real de la marca.'], ['Servicio personalizado', 'Planificación según cada empresa.'], ['Experiencia textil', 'Atención a moquetas y tapicerías.'], ['Cobertura regional', 'Sabadell, Barcelona y Vallès.']].map(([title, text]) => <article key={title} className="rounded-2xl border border-slate-200 p-7"><Sparkles className="h-6 w-6 text-brand-600" /><h3 className="mt-5 font-bold">{title}</h3><p className="mt-3 text-sm leading-6 text-slate-600">{text}</p></article>)}</div></div></section>

    <section className="bg-slate-50 px-4 py-24 text-center sm:px-6 lg:px-8"><MapPin className="mx-auto h-9 w-9 text-brand-600" /><h2 className="mt-5 text-3xl font-black tracking-tight sm:text-4xl">Cobertura en Barcelona y Vallès Occidental</h2><p className="mx-auto mt-5 max-w-3xl text-lg leading-8 text-slate-600">Prestamos servicio en Sabadell, Terrassa, Sant Cugat, Rubí, Cerdanyola, Barberà, Barcelona y otras zonas del Vallès Occidental.</p></section>

    <section className="px-4 py-24 sm:px-6 lg:px-8"><div className="mx-auto max-w-4xl"><div className="text-center"><p className="text-sm font-extrabold uppercase tracking-[0.2em] text-brand-600">Preguntas frecuentes</p><h2 className="mt-3 text-3xl font-black tracking-tight sm:text-4xl">Sobre el mantenimiento de limpieza</h2></div><div className="mt-12 space-y-3">{cleaningMaintenanceFaqs.map((faq) => <details key={faq.question} className="group rounded-2xl border border-slate-200 p-5 open:border-brand-300"><summary className="flex cursor-pointer list-none items-center justify-between gap-4 font-bold">{faq.question}<ChevronDown className="h-5 w-5 shrink-0 text-brand-600 transition group-open:rotate-180" /></summary><p className="mt-4 pr-8 leading-7 text-slate-600">{faq.answer}</p></details>)}</div></div></section>

    <section className="px-4 pb-24 sm:px-6 lg:px-8"><div className="mx-auto max-w-5xl rounded-3xl bg-gradient-to-br from-brand-700 to-teal-600 px-7 py-14 text-center text-white shadow-soft sm:px-12"><p className="text-sm font-extrabold uppercase tracking-[0.2em] text-emerald-100">Presupuesto personalizado</p><h2 className="mt-3 text-3xl font-black tracking-tight sm:text-4xl">Planifiquemos el mantenimiento de tu empresa</h2><p className="mx-auto mt-4 max-w-2xl text-lg leading-8 text-emerald-50">Cuéntanos qué espacios y frecuencia necesitas para preparar una propuesta adaptada.</p><a href={budgetUrl} target="_blank" rel="noreferrer" className="mt-8 inline-flex min-h-12 items-center gap-2 rounded-full bg-white px-7 py-3.5 font-bold text-brand-700">Solicitar presupuesto <ArrowRight className="h-5 w-5" /></a></div></section>
  </>;
}
