import { ArrowRight, Building2, CalendarCheck, Check, ChevronDown, Clock3, Factory, MapPin, MessageCircle, Sparkles, Warehouse } from 'lucide-react';
import { Link } from 'react-router-dom';
import { SEOMeta } from '@/components/SEOMeta';
import { ServicePageSchema } from '@/components/ServicePageSchema';
import { businessConfig, whatsappUrl } from '@/config/business';
import { industrialCleaningFaqs } from '@/content/servicePages';
import { industrialCleaningSEO } from '@/config/seo';

const budgetUrl = whatsappUrl('Hola, quiero solicitar un presupuesto de limpieza para una nave industrial.');
const spaces = ['Naves industriales', 'Almacenes', 'Centros logísticos', 'Zonas de carga', 'Espacios de trabajo', 'Oficinas internas', 'Zonas comunes'];
const needs = ['Suelos y zonas de paso', 'Polvo en superficies accesibles', 'Vestuarios y aseos', 'Zonas comunes', 'Áreas administrativas', 'Limpieza puntual', 'Mantenimiento periódico'];

export function IndustrialCleaningPage() {
  return <>
    <SEOMeta config={industrialCleaningSEO} />
    <ServicePageSchema name="Limpieza profesional de naves industriales" serviceType="Limpieza de naves industriales, almacenes y centros logísticos" path="/limpieza-de-naves-industriales/" breadcrumbName="Limpieza de naves industriales" faqs={industrialCleaningFaqs} />

    <section className="relative isolate overflow-hidden bg-brand-950 px-4 pb-24 pt-36 text-white sm:px-6 lg:px-8"><div className="absolute inset-0 -z-10 bg-[radial-gradient(circle_at_78%_25%,rgba(16,185,129,0.27),transparent_35%)]" /><div className="mx-auto max-w-7xl"><nav aria-label="Migas de pan" className="mb-10 flex items-center gap-2 text-sm text-slate-400"><Link to="/" className="transition hover:text-brand-400">Inicio</Link><span aria-hidden="true">/</span><span className="text-slate-200">Limpieza de naves industriales</span></nav><div className="grid items-center gap-12 lg:grid-cols-[1.15fr_.85fr]"><div><p className="inline-flex items-center gap-2 rounded-full border border-brand-400/30 bg-brand-400/10 px-4 py-2 text-sm font-semibold text-brand-400"><Factory className="h-4 w-4" aria-hidden="true" /> Servicio para instalaciones profesionales</p><h1 className="mt-6 max-w-4xl text-4xl font-black leading-[1.08] tracking-tight sm:text-5xl lg:text-6xl">Limpieza profesional de naves industriales</h1><p className="mt-6 max-w-2xl text-lg leading-8 text-slate-300">Servicio adaptado a naves, almacenes, centros logísticos y zonas de trabajo en Sabadell, Barcelona y Vallès, con planificación acorde al funcionamiento de cada empresa.</p><div className="mt-9 flex flex-col gap-3 sm:flex-row"><a href={budgetUrl} target="_blank" rel="noreferrer" className="inline-flex min-h-12 items-center justify-center gap-2 rounded-full bg-gradient-to-r from-brand-600 to-teal-500 px-6 py-3.5 font-bold shadow-soft transition hover:brightness-110">Solicitar presupuesto <ArrowRight className="h-5 w-5" aria-hidden="true" /></a><a href={budgetUrl} target="_blank" rel="noreferrer" className="inline-flex min-h-12 items-center justify-center gap-2 rounded-full border border-white/20 bg-white/5 px-6 py-3.5 font-bold transition hover:bg-white/10"><MessageCircle className="h-5 w-5 text-brand-400" aria-hidden="true" /> WhatsApp</a></div></div><div className="rounded-3xl border border-white/10 bg-white/[0.07] p-7 backdrop-blur sm:p-9"><Warehouse className="h-10 w-10 text-brand-400" aria-hidden="true" /><p className="mt-6 text-sm font-bold uppercase tracking-[0.18em] text-brand-400">Servicio dimensionado para tu espacio</p><ul className="mt-6 space-y-4 text-slate-200">{['Alcance definido con la empresa', 'Frecuencia según uso y actividad', 'Horarios previamente acordados', 'Cobertura en Barcelona y Vallès'].map((item) => <li key={item} className="flex gap-3"><Check className="mt-0.5 h-5 w-5 shrink-0 text-brand-400" aria-hidden="true" />{item}</li>)}</ul></div></div></div></section>

    <nav aria-label="Contenido de la página" className="border-b border-slate-200 bg-white px-4 sm:px-6 lg:px-8"><div className="mx-auto flex max-w-7xl gap-2 overflow-x-auto py-4"><a href="#espacios" className="shrink-0 rounded-full bg-brand-50 px-4 py-2 text-sm font-bold text-brand-700">Tipos de espacio</a><a href="#mantenimiento" className="shrink-0 rounded-full bg-brand-50 px-4 py-2 text-sm font-bold text-brand-700">Mantenimiento</a><Link to={businessConfig.urls.businessServices.carpets} className="shrink-0 rounded-full bg-slate-100 px-4 py-2 text-sm font-bold text-slate-700">Limpieza textil</Link></div></nav>

    <section id="espacios" className="scroll-mt-24 px-4 py-24 sm:px-6 lg:px-8"><div className="mx-auto max-w-7xl"><div className="max-w-3xl"><p className="text-sm font-extrabold uppercase tracking-[0.2em] text-brand-600">Tipos de espacio</p><h2 className="mt-3 text-3xl font-black tracking-tight sm:text-4xl">Una solución acorde a cada instalación</h2><p className="mt-5 text-lg leading-8 text-slate-600">No todas las naves tienen la misma distribución ni el mismo nivel de uso. El servicio se plantea después de conocer las zonas y la actividad habitual.</p></div><div className="mt-10 grid gap-4 sm:grid-cols-2 lg:grid-cols-3">{spaces.map((item) => <div key={item} className="flex min-h-20 items-center gap-4 rounded-2xl border border-slate-200 bg-white p-5 font-bold shadow-sm"><Building2 className="h-5 w-5 shrink-0 text-brand-600" aria-hidden="true" />{item}</div>)}</div></div></section>

    <section className="bg-slate-50 px-4 py-24 sm:px-6 lg:px-8"><div className="mx-auto grid max-w-7xl gap-14 lg:grid-cols-[.85fr_1.15fr]"><div><p className="text-sm font-extrabold uppercase tracking-[0.2em] text-brand-600">Necesidades de limpieza</p><h2 className="mt-3 text-3xl font-black tracking-tight sm:text-4xl">Atención a las zonas de uso cotidiano</h2><p className="mt-5 text-lg leading-8 text-slate-600">Según las necesidades de la instalación, la propuesta puede incluir superficies y espacios de uso frecuente, sin incorporar trabajos técnicos o especializados que no formen parte del alcance acordado.</p></div><div className="grid grid-cols-1 gap-3 min-[390px]:grid-cols-2">{needs.map((item) => <div key={item} className="flex min-h-20 items-center gap-3 rounded-xl bg-white p-4 font-semibold shadow-sm"><Check className="h-5 w-5 shrink-0 text-brand-600" aria-hidden="true" />{item}</div>)}</div></div></section>

    <section className="bg-brand-950 px-4 py-24 text-white sm:px-6 lg:px-8"><div className="mx-auto grid max-w-7xl items-center gap-12 lg:grid-cols-2"><div><Clock3 className="h-10 w-10 text-brand-400" aria-hidden="true" /><p className="mt-7 text-sm font-extrabold uppercase tracking-[0.2em] text-brand-400">Horarios y operación</p><h2 className="mt-3 text-3xl font-black tracking-tight sm:text-4xl">Planificación para reducir interferencias</h2><p className="mt-5 text-lg leading-8 text-slate-300">El horario se acuerda con la empresa y puede estudiarse antes o después de la actividad, o en franjas programadas que encajen con el funcionamiento de la instalación.</p></div><div className="rounded-3xl border border-white/10 bg-white/[0.06] p-8"><p className="font-bold">Una operativa coordinada</p><p className="mt-3 leading-7 text-slate-300">Zonas, prioridades, accesos y frecuencia se concretan previamente para que el mantenimiento resulte claro y proporcionado.</p></div></div></section>

    <section id="mantenimiento" className="scroll-mt-24 px-4 py-24 sm:px-6 lg:px-8"><div className="mx-auto max-w-7xl"><div className="mx-auto max-w-3xl text-center"><p className="text-sm font-extrabold uppercase tracking-[0.2em] text-brand-600">Mantenimiento</p><h2 className="mt-3 text-3xl font-black tracking-tight sm:text-4xl">Limpieza periódica o puntual según el uso</h2><p className="mt-5 text-lg leading-8 text-slate-600">La frecuencia se define en función de la actividad, el tránsito y las zonas prioritarias. El objetivo es crear un plan personalizado, sin imponer paquetes cerrados.</p><Link to={businessConfig.urls.businessServices.maintenance} className="group mt-5 inline-flex items-center gap-2 font-bold text-brand-700">Ver servicio de limpieza recurrente <ArrowRight className="h-4 w-4 transition group-hover:translate-x-1" /></Link></div><div className="mt-12 grid gap-5 md:grid-cols-3">{[['Puntual', 'Para necesidades concretas o una puesta a punto programada.'], ['Recurrente', 'Para conservar de forma continuada las zonas acordadas.'], ['Frecuencia adaptada', 'Diaria, semanal o según las necesidades reales de uso.']].map(([title, text]) => <article key={title} className="rounded-2xl border border-slate-200 p-7"><CalendarCheck className="h-7 w-7 text-brand-600" aria-hidden="true" /><h3 className="mt-5 text-xl font-bold">{title}</h3><p className="mt-3 leading-7 text-slate-600">{text}</p></article>)}</div></div></section>

    <section className="bg-slate-50 px-4 py-24 sm:px-6 lg:px-8"><div className="mx-auto grid max-w-7xl items-center gap-12 lg:grid-cols-2"><div><p className="text-sm font-extrabold uppercase tracking-[0.2em] text-brand-600">Áreas administrativas</p><h2 className="mt-3 text-3xl font-black tracking-tight sm:text-4xl">Oficinas y textiles dentro de la nave</h2><p className="mt-5 text-lg leading-8 text-slate-600">Cuando la instalación incorpora despachos, salas o recepción, también podemos valorar sus moquetas, sillas y tapicerías como parte de una propuesta coordinada.</p></div><div className="grid gap-4"><Link to={businessConfig.urls.businessServices.offices} className="group flex items-center justify-between rounded-2xl bg-white p-6 font-bold shadow-sm ring-1 ring-slate-200 transition hover:ring-brand-400">Limpieza de oficinas <ArrowRight className="h-5 w-5 text-brand-600 transition group-hover:translate-x-1" /></Link><Link to={businessConfig.urls.businessServices.carpets} className="group flex items-center justify-between rounded-2xl bg-white p-6 font-bold shadow-sm ring-1 ring-slate-200 transition hover:ring-brand-400">Moquetas y tapicerías para empresas <ArrowRight className="h-5 w-5 text-brand-600 transition group-hover:translate-x-1" /></Link></div></div></section>

    <section className="px-4 py-24 sm:px-6 lg:px-8"><div className="mx-auto max-w-7xl"><div className="mx-auto max-w-3xl text-center"><p className="text-sm font-extrabold uppercase tracking-[0.2em] text-brand-600">Por qué Superclim</p><h2 className="mt-3 text-3xl font-black tracking-tight sm:text-4xl">Experiencia aplicada al entorno empresarial</h2></div><div className="mt-12 grid gap-5 sm:grid-cols-2 lg:grid-cols-4">{[['Más de 16 años', 'Trayectoria real de la marca Superclim.'], ['Servicio personalizado', 'Alcance adaptado a cada instalación.'], ['Experiencia textil', 'Atención específica a zonas administrativas.'], ['Cobertura regional', 'Sabadell, Barcelona y Vallès Occidental.']].map(([title, text]) => <article key={title} className="rounded-2xl border border-slate-200 p-7"><Sparkles className="h-6 w-6 text-brand-600" /><h3 className="mt-5 font-bold">{title}</h3><p className="mt-3 text-sm leading-6 text-slate-600">{text}</p></article>)}</div></div></section>

    <section className="bg-slate-50 px-4 py-24 text-center sm:px-6 lg:px-8"><MapPin className="mx-auto h-9 w-9 text-brand-600" /><h2 className="mt-5 text-3xl font-black tracking-tight sm:text-4xl">Cobertura en Barcelona y Vallès Occidental</h2><p className="mx-auto mt-5 max-w-3xl text-lg leading-8 text-slate-600">Atendemos instalaciones en Sabadell, Terrassa, Sant Cugat, Rubí, Cerdanyola, Barberà, Barcelona y otras zonas del Vallès Occidental.</p></section>

    <section className="px-4 py-24 sm:px-6 lg:px-8"><div className="mx-auto max-w-4xl"><div className="text-center"><p className="text-sm font-extrabold uppercase tracking-[0.2em] text-brand-600">Preguntas frecuentes</p><h2 className="mt-3 text-3xl font-black tracking-tight sm:text-4xl">Sobre la limpieza de naves</h2></div><div className="mt-12 space-y-3">{industrialCleaningFaqs.map((faq) => <details key={faq.question} className="group rounded-2xl border border-slate-200 bg-white p-5 open:border-brand-300"><summary className="flex cursor-pointer list-none items-center justify-between gap-4 font-bold focus-visible:outline-none">{faq.question}<ChevronDown className="h-5 w-5 shrink-0 text-brand-600 transition group-open:rotate-180" /></summary><p className="mt-4 pr-8 leading-7 text-slate-600">{faq.answer}</p></details>)}</div></div></section>

    <section className="px-4 pb-24 sm:px-6 lg:px-8"><div className="mx-auto max-w-5xl rounded-3xl bg-gradient-to-br from-brand-700 to-teal-600 px-7 py-14 text-center text-white shadow-soft sm:px-12"><p className="text-sm font-extrabold uppercase tracking-[0.2em] text-emerald-100">Presupuesto adaptado</p><h2 className="mt-3 text-3xl font-black tracking-tight sm:text-4xl">Cuéntanos cómo es tu instalación</h2><p className="mx-auto mt-4 max-w-2xl text-lg leading-8 text-emerald-50">Valoraremos zonas, actividad y frecuencia para preparar una propuesta personalizada.</p><a href={budgetUrl} target="_blank" rel="noreferrer" className="mt-8 inline-flex min-h-12 items-center gap-2 rounded-full bg-white px-7 py-3.5 font-bold text-brand-700">Solicitar presupuesto <ArrowRight className="h-5 w-5" /></a></div></section>
  </>;
}
