import { ArrowRight, Armchair, Check, ChevronDown, Clock3, MapPin, MessageCircle, ShoppingBag, Sparkles, Store } from 'lucide-react';
import { Link } from 'react-router-dom';
import { SEOMeta } from '@/components/SEOMeta';
import { ServicePageSchema } from '@/components/ServicePageSchema';
import { businessConfig, whatsappUrl } from '@/config/business';
import { retailCleaningFaqs } from '@/content/servicePages';
import { retailCleaningSEO } from '@/config/seo';

const budgetUrl = whatsappUrl('Hola, quiero solicitar un presupuesto de limpieza para un local comercial.');
const spaces = ['Tiendas', 'Comercios', 'Showrooms', 'Recepciones', 'Locales de atención', 'Zonas internas'];
const zones = [
  ['Atención al público', 'Entradas, recepción, zonas de paso y espacios donde se recibe al cliente.'],
  ['Suelos y superficies', 'Atención ajustada al material, el tránsito y el uso habitual del local.'],
  ['Aseos', 'Limpieza integrada en el alcance acordado para el establecimiento.'],
  ['Zonas internas', 'Almacén, descanso u otras áreas accesibles según las necesidades del negocio.'],
];

export function RetailCleaningPage() {
  return <>
    <SEOMeta config={retailCleaningSEO} />
    <ServicePageSchema name="Limpieza profesional de locales comerciales" serviceType="Limpieza de tiendas, comercios y locales profesionales" path="/limpieza-de-locales-comerciales/" breadcrumbName="Limpieza de locales comerciales" faqs={retailCleaningFaqs} />

    <section className="relative isolate overflow-hidden bg-brand-950 px-4 pb-24 pt-36 text-white sm:px-6 lg:px-8"><div className="absolute inset-0 -z-10 bg-[radial-gradient(circle_at_78%_25%,rgba(16,185,129,0.27),transparent_35%)]" /><div className="mx-auto max-w-7xl"><nav aria-label="Migas de pan" className="mb-10 flex items-center gap-2 text-sm text-slate-400"><Link to="/" className="hover:text-brand-400">Inicio</Link><span aria-hidden="true">/</span><span className="text-slate-200">Limpieza de locales comerciales</span></nav><div className="grid items-center gap-12 lg:grid-cols-[1.15fr_.85fr]"><div><p className="inline-flex items-center gap-2 rounded-full border border-brand-400/30 bg-brand-400/10 px-4 py-2 text-sm font-semibold text-brand-400"><ShoppingBag className="h-4 w-4" /> Servicio para comercios</p><h1 className="mt-6 max-w-4xl text-4xl font-black leading-[1.08] tracking-tight sm:text-5xl lg:text-6xl">Limpieza profesional de locales comerciales</h1><p className="mt-6 max-w-2xl text-lg leading-8 text-slate-300">Limpieza puntual o mantenimiento para tiendas y locales en Sabadell, Barcelona y Vallès, adaptada al horario, el tránsito y la actividad de cada negocio.</p><div className="mt-9 flex flex-col gap-3 sm:flex-row"><a href={budgetUrl} target="_blank" rel="noreferrer" className="inline-flex min-h-12 items-center justify-center gap-2 rounded-full bg-gradient-to-r from-brand-600 to-teal-500 px-6 py-3.5 font-bold shadow-soft hover:brightness-110">Solicitar presupuesto <ArrowRight className="h-5 w-5" /></a><a href={budgetUrl} target="_blank" rel="noreferrer" className="inline-flex min-h-12 items-center justify-center gap-2 rounded-full border border-white/20 bg-white/5 px-6 py-3.5 font-bold hover:bg-white/10"><MessageCircle className="h-5 w-5 text-brand-400" /> WhatsApp</a></div></div><div className="rounded-3xl border border-white/10 bg-white/[0.07] p-7 sm:p-9"><Store className="h-10 w-10 text-brand-400" /><p className="mt-6 text-sm font-bold uppercase tracking-[0.18em] text-brand-400">Un local preparado para recibir</p><ul className="mt-6 space-y-4 text-slate-200">{['Alcance adaptado al negocio', 'Atención a zonas de tránsito', 'Servicio puntual o recurrente', 'Horarios acordados'].map((item) => <li key={item} className="flex gap-3"><Check className="h-5 w-5 shrink-0 text-brand-400" />{item}</li>)}</ul></div></div></div></section>

    <nav aria-label="Contenido de la página" className="border-b border-slate-200 px-4 sm:px-6 lg:px-8"><div className="mx-auto flex max-w-7xl gap-2 overflow-x-auto py-4"><a href="#locales" className="shrink-0 rounded-full bg-brand-50 px-4 py-2 text-sm font-bold text-brand-700">Tipos de locales</a><a href="#mantenimiento" className="shrink-0 rounded-full bg-brand-50 px-4 py-2 text-sm font-bold text-brand-700">Mantenimiento</a><Link to="/" className="shrink-0 rounded-full bg-slate-100 px-4 py-2 text-sm font-bold">Superclim Empresas</Link></div></nav>

    <section id="locales" className="scroll-mt-24 px-4 py-24 sm:px-6 lg:px-8"><div className="mx-auto max-w-7xl"><div className="max-w-3xl"><p className="text-sm font-extrabold uppercase tracking-[0.2em] text-brand-600">Tipos de locales</p><h2 className="mt-3 text-3xl font-black tracking-tight sm:text-4xl">Una solución para distintos espacios comerciales</h2><p className="mt-5 text-lg leading-8 text-slate-600">Cada establecimiento tiene una distribución, un tránsito y unos horarios propios. El servicio se define después de conocer el espacio y sus prioridades.</p></div><div className="mt-10 grid gap-4 sm:grid-cols-2 lg:grid-cols-3">{spaces.map((space) => <div key={space} className="flex min-h-20 items-center gap-4 rounded-2xl border border-slate-200 p-5 font-bold shadow-sm"><ShoppingBag className="h-5 w-5 shrink-0 text-brand-600" />{space}</div>)}</div></div></section>

    <section className="bg-slate-50 px-4 py-24 sm:px-6 lg:px-8"><div className="mx-auto max-w-7xl"><div className="mx-auto max-w-3xl text-center"><p className="text-sm font-extrabold uppercase tracking-[0.2em] text-brand-600">Zonas del local</p><h2 className="mt-3 text-3xl font-black tracking-tight sm:text-4xl">Atención al público y espacios internos</h2></div><div className="mt-12 grid gap-5 sm:grid-cols-2 lg:grid-cols-4">{zones.map(([title, text]) => <article key={title} className="rounded-2xl bg-white p-7 shadow-sm"><Sparkles className="h-7 w-7 text-brand-600" /><h3 className="mt-5 font-bold">{title}</h3><p className="mt-3 text-sm leading-6 text-slate-600">{text}</p></article>)}</div></div></section>

    <section id="mantenimiento" className="scroll-mt-24 px-4 py-24 sm:px-6 lg:px-8"><div className="mx-auto grid max-w-7xl items-center gap-12 lg:grid-cols-2"><div><p className="text-sm font-extrabold uppercase tracking-[0.2em] text-brand-600">Puntual o periódico</p><h2 className="mt-3 text-3xl font-black tracking-tight sm:text-4xl">Limpieza según el ritmo del comercio</h2><p className="mt-5 text-lg leading-8 text-slate-600">El servicio puede responder a una necesidad puntual o convertirse en un mantenimiento recurrente. La frecuencia se plantea según la actividad, el tránsito y las zonas prioritarias.</p><Link to={businessConfig.urls.businessServices.maintenance} className="group mt-6 inline-flex items-center gap-2 font-bold text-brand-700">Conocer el mantenimiento periódico <ArrowRight className="h-4 w-4 transition group-hover:translate-x-1" /></Link></div><div className="rounded-3xl bg-brand-50 p-8"><Clock3 className="h-9 w-9 text-brand-600" /><h3 className="mt-5 text-xl font-bold">Horarios adaptados</h3><p className="mt-3 leading-7 text-slate-600">Podemos estudiar franjas antes de la apertura, después del cierre o en momentos acordados para minimizar interferencias en la atención al público.</p></div></div></section>

    <section className="bg-brand-950 px-4 py-24 text-white sm:px-6 lg:px-8"><div className="mx-auto grid max-w-7xl items-center gap-12 lg:grid-cols-[.85fr_1.15fr]"><div className="rounded-3xl border border-white/10 bg-white/[0.06] p-8"><Armchair className="h-12 w-12 text-brand-400" /><div className="mt-8 grid grid-cols-2 gap-3">{['Sillas', 'Bancos', 'Tapicerías', 'Moquetas'].map((item) => <div key={item} className="rounded-xl bg-white/[0.07] p-4 text-sm font-bold">{item}</div>)}</div></div><div><p className="text-sm font-extrabold uppercase tracking-[0.2em] text-brand-400">Textiles comerciales</p><h2 className="mt-3 text-3xl font-black tracking-tight sm:text-4xl">Sillas, tapicerías y moquetas cuando aplica</h2><p className="mt-5 text-lg leading-8 text-slate-300">Cuando el local incorpora asientos, bancos o superficies textiles, la experiencia especializada de Superclim permite valorar su limpieza de manera específica.</p><Link to={businessConfig.urls.businessServices.carpets} className="group mt-6 inline-flex items-center gap-2 font-bold text-brand-400">Ver limpieza textil profesional <ArrowRight className="h-4 w-4 transition group-hover:translate-x-1" /></Link></div></div></section>

    <section className="px-4 py-24 text-center sm:px-6 lg:px-8"><MapPin className="mx-auto h-9 w-9 text-brand-600" /><h2 className="mt-5 text-3xl font-black tracking-tight sm:text-4xl">Locales en Barcelona, Sabadell y Vallès</h2><p className="mx-auto mt-5 max-w-3xl text-lg leading-8 text-slate-600">Atendemos comercios en Sabadell, Terrassa, Sant Cugat, Rubí, Cerdanyola, Barberà, Barcelona y otras zonas del Vallès Occidental.</p></section>

    <section className="bg-slate-50 px-4 py-24 sm:px-6 lg:px-8"><div className="mx-auto max-w-4xl"><div className="text-center"><p className="text-sm font-extrabold uppercase tracking-[0.2em] text-brand-600">Preguntas frecuentes</p><h2 className="mt-3 text-3xl font-black tracking-tight sm:text-4xl">Sobre la limpieza de locales</h2></div><div className="mt-12 space-y-3">{retailCleaningFaqs.map((faq) => <details key={faq.question} className="group rounded-2xl border border-slate-200 bg-white p-5 open:border-brand-300"><summary className="flex cursor-pointer list-none items-center justify-between gap-4 font-bold">{faq.question}<ChevronDown className="h-5 w-5 shrink-0 text-brand-600 transition group-open:rotate-180" /></summary><p className="mt-4 pr-8 leading-7 text-slate-600">{faq.answer}</p></details>)}</div></div></section>

    <section className="px-4 py-24 sm:px-6 lg:px-8"><div className="mx-auto max-w-5xl rounded-3xl bg-gradient-to-br from-brand-700 to-teal-600 px-7 py-14 text-center text-white shadow-soft sm:px-12"><p className="text-sm font-extrabold uppercase tracking-[0.2em] text-emerald-100">Presupuesto personalizado</p><h2 className="mt-3 text-3xl font-black tracking-tight sm:text-4xl">Una propuesta adaptada a tu local</h2><p className="mx-auto mt-4 max-w-2xl text-lg leading-8 text-emerald-50">Cuéntanos cómo es el espacio, sus horarios y la frecuencia que necesitas.</p><a href={budgetUrl} target="_blank" rel="noreferrer" className="mt-8 inline-flex min-h-12 items-center gap-2 rounded-full bg-white px-7 py-3.5 font-bold text-brand-700">Solicitar presupuesto <ArrowRight className="h-5 w-5" /></a></div></section>
  </>;
}
